### ISSUE TITLE
Reason is not defined

### ISSUE THREAD

**Issue by mirobotur** [twilio-professional-services/flex-project-template#111]
Will this work?
I tested the same approach and it ends up with 
`failed after 0 retry attempts, status code: 500, message: reason is not defined`

https://github.com/twilio-professional-services/flex-project-template/blob/69d3edea836c7f2e23831dad9cbaabe76b6cc188/serverless-functions/src/functions/common/twilio-wrappers/sync.private.js#L47

**Comment by dremin** [comment]
Ah, I see what is happening here and will fix. However, there's another issue causing your Sync docs to not be created, I would suggest double checking the Sync service SID in your .env.
