### ISSUE TITLE
Multi-Call Issue

### ISSUE THREAD

**Issue by NathanFeeser** [twilio-professional-services/flex-project-template#121]
When I have the multi call handling feature enabled and go to accept a second call (which should hold+mute the first call) it results in the below error. Also a constant beeping that doesn't go away until I reload the page entirely.

![image](https://user-images.githubusercontent.com/595949/209451173-0d5b48ed-3ddf-4f58-a6cc-04af4ee664d0.png)

**Comment by dremin** [comment]
Could you please check which version of the plugin are you running? I recently made a fix in this area in version 9.0.40.

**Comment by NathanFeeser** [comment]
Yes, I'm on v9.0.40. I'm using this to take multiple external calls (not only internal transfers), and this was working as of a few weeks ago, but I get the above error after pulling in the latest updates.

**Comment by dremin** [comment]
Ah, interesting! Thanks for the details, I'm now able to reproduce and will investigate.

**Comment by dremin** [comment]
This should now be fixed in the latest version, 9.0.42. Thanks for the report!

**Comment by NathanFeeser** [comment]
Excellent, thank you so much @dremin!
