### ISSUE TITLE
Chat transfer button not showing in directory

### ISSUE THREAD

**Issue by chouputra** [twilio-professional-services/flex-project-template#128]
Chat transfer button not showing because of incorrect logic in ShowDirectory.ts, the fix:

`// Hide consult transfer for non-CBM task
      if (!Flex.TaskHelper.isCBMTask(Flex.TaskHelper.getTaskByTaskSid(taskSid))) {
        display = "none";
      }`

**Comment by dremin** [comment]
This is intentional. However, #71 just merged and has added proper support for warm transfer of conversation-based messaging tasks.
