### ISSUE TITLE
Enhancement: Support more than two multi-calls

### ISSUE THREAD

**Issue by restacall** [twilio-professional-services/flex-project-template#133]
Do you think it would be difficult to support more than just two calls at a time? I was thinking it could be as simple as storing a list of calls and devices, destroying and adding as calls are coming in, but maybe there's more to it? Thanks!

**Comment by dremin** [comment]
Hi @restacall! Apologies this took so long, but I am working on a branch that enables this. I'd love to hear more information regarding your use case for 3+ calls so that I can validate that this will work for you as well.
