### ISSUE TITLE
Bug: Error for video-app-quickstart "npm run build" on Windows

### ISSUE THREAD

**Issue by leroychan** [twilio-professional-services/flex-project-template#251]
File: `web-app-examples/video-app-quickstart/package.json`
Command: `npm run build`
Issue with the following command: `rm -rfv ../../serverless-functions/src/assets/features/chat-to-video/ && mkdir ../../serverless-functions/src/assets/features/chat-to-video/ && cp -R ./out/* ../../serverless-functions/src/assets/features/chat-to-video/`

Windows do not have the `rm` command natively in Command Shell / Power Shell.

**Comment by dremin** [comment]
Does it work in Git Bash by chance?

**Comment by dremin** [comment]
Closing due to being stale, but this works correctly in Windows when using bash in my recent testing.
