### ISSUE TITLE
Can't disable admin_ui feature after enabling it

### ISSUE THREAD

**Issue by RusinovIG** [twilio-professional-services/flex-project-template#287]
I can't disable `admin_ui` feature, after it was enabled once.
I deployed new configuration changes and remote config from https://flex-api.twilio.com/v1/Configuration has:
`"admin_ui": {
  "enabled": false
}`
However in the UI I still see admin page to edit plugin features and my updates to the remote configuration are not reflected in the UI.
![image](https://github.com/twilio-professional-services/flex-project-template/assets/1404336/b6b01707-3c25-4d44-a804-6cf9cda4593e)

**Comment by jhunter-twilio** [comment]
Hello @RusinovIG 

Just to confirm, when you are performing your deploy are you checking the box that says "Overwrite config set by Admin UI panel" as seen in this screenshot 

![screenshot](https://twilio-professional-services.github.io/flex-project-template/assets/images/github-trigger-89d4771bd58fb404e13cedda533b1007.png)
