### ISSUE TITLE
activity-reservation-handler automatically overrides the agent's status and changes it to available

### ISSUE THREAD

**Issue by matiasdipaolo** [twilio-professional-services/flex-project-template#290]
If an agent sets their status as offline and there is a task that can be assigned to them, Twilio automatically overrides the agent's status and changes it to available.
--> Please see:[Issue example]( https://drive.google.com/file/d/1mZ8D8Lu2YYSnaOKovoRZeeESUoN2xEOz/view?usp=drive_link )
Looks to be an issue with the “activity-reservation-handler” feature that queues up the activity change. So we should look into this. For some reason, possibly due to the active reservation being present on the agent, the activity change (e.g. to “Break”) is also queuing up a pending activity change of “Available”. So as soon as the reservation ends, that pending activity change executes - putting the agent available again.

**Comment by jhunter-twilio** [comment]
@matiasdipaolo - thanks for the feedback, looking into it!
