### ISSUE TITLE
Chat to video escalation plugin functionality error

### ISSUE THREAD

**Issue by JorgeF55** [twilio-professional-services/flex-project-template#299]
After compiling and testing the Chat to video escalation plugin, it can be seen that it works correctly in the agent interface in flex.
![image](https://github.com/twilio-professional-services/flex-project-template/assets/137451189/bd98544e-7bb0-4d9b-9aae-1c5e4c0c4058)

but when opening the link to connect the client's video it does not work:
![image](https://github.com/twilio-professional-services/flex-project-template/assets/137451189/03092ca6-4576-47f1-968c-0c0a53d06946)
![image](https://github.com/twilio-professional-services/flex-project-template/assets/137451189/47ee4c9a-069d-4f75-a2c0-f79794f13fc1)

clicking the red button gives the following error
![image](https://github.com/twilio-professional-services/flex-project-template/assets/137451189/0299bb9f-bf38-4c52-a534-59dff8b181ad)

**Comment by dremin** [comment]
@JorgeF55 This should now be working properly with the latest deployment scripts.

**Comment by dremin** [comment]
Closing now that video has been completely overhauled. This should work out-of-the-box now; please feel free to re-open this issue if you continue to have the issue after the updates!
