### ISSUE TITLE
TypeScript errors running "Deploy Flex" from GitHub actions (and also running locally)

### ISSUE THREAD

**Issue by SlvBlz** [twilio-professional-services/flex-project-template#306]
Hi!

I'm able to run all the jobs in flex-project-template except "Deploy Flex". The "deploy-release-plugin" keeps failing with TypeScript errors. I attempted to run it locally using the CLI and I get the exact same errors as I do on GitHub.

I've tried running on different Node versions locally (as that's worked in other instances) but I keep getting the same errors. I didn't make any changes to the source code. Here are a few examples of the compile errors (with some of the path removed):

Failed to compile plugin plugin-flex-ts-template-v2.

Error 1:
src/feature-library/activity-reservation-handler/custom-components/pending-activity/PendingActivityComponent.tsx
Property 'name' does not exist on type 'typeof import("plugin-flex-ts-template-v2/node_modules/twilio-taskrouter/dist/declarations/Activity")'.  TS2339

24 |   return (
25 |     <>
->26 |       {pendingActivity && pendingActivity.name !== Manager.getInstance().workerClient?.activity.name && (
      |                                                                                                 ^
27 |         <Flex vertical marginRight="space20" hAlignContent="center">
28 |           <Text as="p" color="colorTextInverse" fontSize="fontSize20" fontWeight="fontWeightBold">
29 |             <Template source={templates[StringTemplates.PendingActivity]} />

Error 2:
src/feature-library/omni-channel-capacity-management/flex-hooks/actions/AcceptTask.ts
Type 'typeof import("plugin-flex-ts-template-v2/node_modules/twilio-taskrouter/dist/declarations/Channel") | undefined' is not assignable to type 'Channel | undefined'.
Type 'typeof import("plugin-flex-ts-template-v2/node_modules/twilio-taskrouter/dist/declarations/Channel")' is missing the following properties from type 'Channel': accountSid, available, availableCapacityPercentage, capacity, and 7 more.  TS2322

47 |
48 |     const workerChannelsArray = workerChanneslMap ? Array.from(workerChanneslMap.values()) : null;
  -> 49 |     const configuredChannel: Channel | undefined = workerChannelsArray
          |           ^
50 |       ? workerChannelsArray.find((channel) => {
51 |           return channel?.taskChannelUniqueName === channelFromConfig;
52 |         })

There are 2 more errors like this. Any help would be greatly appreciated.

Thanks!

**Comment by dremin** [comment]
Hi @SlvBlz! We actually just merged a fix for this (#305), if you grab those changes you should be good to go.

Please let me know if that helps!
