### ISSUE TITLE
External Cold Transfers failing if Account has conference attributes enabled by default

### ISSUE THREAD

**Issue by stjohnson44** [twilio-professional-services/flex-project-template#335]
Small issue I encountered with call transfers. If an account has the conference and participant attributes enabled for outbound calls, by default the call_sid attribute is not passed to the task. In this case the transfers fail because the `StartExternalColdTransfer` action passes in `task.attributes.call_sid` directly to the `startColdTransfer` function from the `CustomTransferDirectoryService`. Suggested fix is defining the call sid similarly to this: 
`const callSid = task?.attributes?.call_sid ? task.attributes.call_sid : task.attributes.conference.participants.customer`

**Comment by dremin** [comment]
Thanks for letting us know about this issue!
