### ISSUE TITLE
Teams View Filter does not reflect the filters on closing and then re-opening

### ISSUE THREAD

**Issue by vinitdave27** [twilio-professional-services/flex-project-template#352]
The Teams View Filter feature allows the supervisor to select and specify certain filters. Although, if the supervisor closes the filter side panel or navigates to another view and comes back to the teams view the next time the filter side panel is opened, the filters previously applied are not visible in the UI.

There is no easy way for the supervisor to view the previously applied filters except for changing the filter again using the side panel.

**Comment by dremin** [comment]
I'm not able to reproduce this. Are you using the latest version of the template and Flex?

**Comment by dremin** [comment]
Unfortunately we don't update the version in json very often, but you should be able to use the git log to see what commit was pulled. There were some fixes around team view filters recently, especially with the multi-select component, in #334.

**Comment by vinitdave27** [comment]
As mentioned by @dremin , the issue is resolved in the subsequent release of the feature template.
