### ISSUE TITLE
Serverless URL Mapping Error when 2 Flex Project Templates are running on a single Flex instance 

### ISSUE THREAD

**Issue by leroychan** [twilio-professional-services/flex-project-template#380]
**Setup**
Single Flex Instance running the following:
1. Vanilla Flex Project Template (Deployed using Github Actions)
2. Custom Flex Project Template with "removed features" and "rename template" - i.e. standalone features built using Flex Project Template structure

**Issue**
Flex plugin not able to read the correct serverless URL using "this.serverlessDomain". It defaults to the "custom-flex-extensions-serverless" which is the serverless URL that is created with the original Flex Project Template.

Potential Solution
When running "rename template", we need to modify the following:
1. "scripts/config/mappings.json" - SERVERLESS_DOMAIN
2. "flex-template-XXX/src/utils/serverless/ApiService/index.ts" Ensure the "custom_data" portion is renamed and not appended
3. terraform scripts serverless domain lookup should user the new domain name

**Comment by jhunter-twilio** [comment]
Hi @leroychan 

I added a PR to address this and #379 - i wasn't clear on point 2 above though - i believe its addressed but would like to confirm with you.
