### ISSUE TITLE
Twilio serverless deployment error

### ISSUE THREAD

**Issue by JuanSanabria-SEAQ** [twilio-professional-services/flex-project-template#423]
Good morning

I am communicating by this means because I am deploying my serverless via GitHub actions, but I get the following error when performing this action 

I would like to know why and how I can solve it.

I attach evidence
![image](https://github.com/twilio-professional-services/flex-project-template/assets/136838656/92aa2bd2-87a5-49f2-be6a-c269b7899130)
![image](https://github.com/twilio-professional-services/flex-project-template/assets/136838656/20f6d494-fbab-468e-b293-cd2421f3d99f)

**Comment by jhunter-twilio** [comment]
Hi @JuanSanabria-SEAQ 

that should be addressed by #421 and #422

Can you take an update to ensure you have those changes and try again and if you still have an issue can you re-open this one?
