### ISSUE TITLE
How update addons?

### ISSUE THREAD

**Issue by GuilleFibo** [twilio-professional-services/flex-project-template#436]
Hi, I didn't have any problem the first time I used this plugin template, but when I try to update an addon, this update never works.
I'm using npm run deploy-addons to do this
Someone know what is the correct command to update an addon?

**Comment by dremin** [comment]
Hi, could you please clarify your intentions with 'updating an addon'? Are you trying to make a change, deploy, or something else?

**Comment by dremin** [comment]
Closing due to no response--feel free to re-open if necessary. Thanks!
