### ISSUE TITLE
The supervisor cannot publish configured schedules.

### ISSUE THREAD

**Issue by JuanSanabria-SEAQ** [twilio-professional-services/flex-project-template#444]
Good morning

I am contacting by this means because currently the supervisors of my contact center can not make schedule changes in the schedules manager. I would like to know how I can solve this.

**Comment by dremin** [comment]
Hi @JuanSanabria-SEAQ, there are a couple changes to make in order for supervisors to make changes:
1. In `plugin-flex-ts-template-v2/src/feature-library/schedule-manager/utils/schedule-manager.ts`, modify the `canShowScheduleManager` function to check for the `supervisor` role in addition to `admin`.
2. In `addons/serverless-schedule-manager/functions/admin`, update the `publish`, `update-status`, and `update` functions to check for the `supervisor` role in addition to `admin`.
3. Deploy!
