### ISSUE TITLE
Issue when running with Node V18.12.1

### ISSUE THREAD

**Issue by blakecodes** [twilio-professional-services/flex-project-template#446]
Hello, 

I am currently running the 1.1.0 version of this project from the root. When using Node V16, it runs fine. But when attempting to run with V18, the Flex UI spins up but does not load any of the features. 

It specifically spits out this error: 
```
[HPM] Error occurred while trying to proxy request /plugins/plugin-flex-ts-template-v2.js from localhost:3000 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

When running: 
```
npm run start
```

I am prepping to do the upgrade of all of the functions to Node V18 and want to test out their functionality locally before attempting to deploy. If you all also have any insight in to how to set the version for the functions to 18, it would be appreciate. The option is locked inside of the Twilio Function UI for this service.

**Comment by dremin** [comment]
Hi @blakecodes! Please make sure that when upgrading to Node 18 that you are using the latest Twilio CLI as well as the latest Flex CLI and Serverless CLI plugins. These all had several issues on Node 18 that have been somewhat recently fixed.
