### ISSUE TITLE
Transcript missing on Webchat Transfer 

### ISSUE THREAD

**Issue by alankleindev** [twilio-professional-services/flex-project-template#447]
Hello, we are testing out the Twilio Flex Plugin from the Plugin Library, Chat Transfer - the latest version - 2.0.0 with Flex 2.4.1. What we noticed is then the first webchat cold transfer happens, the receiving agent can see the full transcript.

However, when that agent transfers the chat back to the original agent, the original agent is unable to see the transcript or any messages they type in the Flex UI to send to the customer. If that agent does a browser refresh of the Flex UI (by going up to the address bar and hitting enter), the UI is again rendered correctly and they can see the full transcript and see the messages they are typing to the customer.

**Comment by dremin** [comment]
Hi @alankleindev, could you please try this in Flex 2.5.0? I am familiar with this bug and saw a change go into 2.5.0 that I believe may fix it.

**Comment by alankleindev** [comment]
It seems so @dremin .We had tested 2.5.0 chat transfer before I saw your response above and it seemed to work, we didn't do exhaustive testing but the few chat transfers we did didn't have that issue where the transcript was missing until the agent refreshed their browser session. Thanks!

**Comment by dremin** [comment]
Great, thanks for confirming! 🎉
