### ISSUE TITLE
Improvements to Conversation Transfer : Cold Transfer

### ISSUE THREAD

**Issue by mster429** [twilio-professional-services/flex-project-template#476]
Hi,
I am using the flex template and I have requirement to remove the transferring agent only when the transfered agent accept the newly created transfer task. As I can see currently it is removing the transferring agent as soon as the new transfer request is created. Any way to get this done ? Thanks in advance

**Comment by dremin** [comment]
Hi @mster429! This should be possible. When performing a cold transfer, the plugin provides a `removeFlexInteractionParticipantSid` parameter to the `invite-participant` serverless function to remove the existing participant during transfer. You would need to modify this logic to not remove the participant at this time, and instead use the separate `remove-participant` serverless function upon task acceptance.

**Comment by mster429** [comment]
Hi @dremin ,
Thanks for your reply. But I am wondering on how to get the task status. Do I need to add custom code there or can I use the existing code and do some modifications to get it done. As I understood we are not checking the task status in the conversation transfer routine anywhere

**Comment by dremin** [comment]
Hi @mster429, there are a few ways you can react to task/reservation acceptance, I'd suggest one of these:
- From the plugin side, using a before/after AcceptTask [action listener](https://twilio-professional-services.github.io/flex-project-template/building/flex-hooks/actions) using the [flex hooks framework](https://twilio-professional-services.github.io/flex-project-template/building/flex-hooks/overview)
- From the server side, using a TaskRouter [event callback](https://www.twilio.com/docs/taskrouter/api/event/reference) for the reservation.accepted event

**Comment by mster429** [comment]
Hi dremin,
I could implement this using the action listener framework. Thanks for your support
