### ISSUE TITLE
Audios have poor quality when captured for sending on WhatsApp

### ISSUE THREAD

**Issue by samuelgomesrosa** [twilio-professional-services/flex-project-template#524]
We are using the send-audio-rec-file plugin, from [flex-project-template](https://www.twilio.com/en-us/blog/introduzindo-the-flex-project-template-developed- by - twilio-professional-services) for sending WhatsApp audio messages. At certain times, some of the operators' audio is randomly of low quality (slow, robotic voice or choppy sound).

The problem can be replicated as follows: while the operator records the audio to send, the customer must send messages.

**Comment by dremin** [comment]
Thanks for the report @samuelgomesrosa! This appears to be a known issue with the library we are using for the recording; we should be able to improve things with some refactoring. I will look into it!
