### ISSUE TITLE
What's the best way to customise the official features/plugins?

### ISSUE THREAD

**Issue by marek-siemieniuk-morawski** [twilio-professional-services/flex-project-template#527]
Hi,

We have a requirement to enhance one of the plugins available in the Marketplace. Specifically, it involves plugin-flex-ts-template-v2/src/feature-library/conference and adding a pick-up list where agents can select a department to redirect calls to. Initially, we addressed this by forking https://github.com/twilio-professional-services/flex-dialpad-addon-plugin, which served us well, but we have concerns about maintainability. The project itself was archived almost a year ago, so in the event of updates from your side, we would need to manually update the fork. Not ideal, I'd say.

I'm wondering if you have any guidelines on how to customize the plugins developed here at Twilio. As mentioned, forking a legacy project doesn't seem like the best approach. Is it possible to modify the ConferenceDialog component externally, from another plugin, by embedding another component within?

Sorry if that's not the place to ask such a question.

Best regards

**Comment by marek-siemieniuk-morawski** [comment]
I wonder if you're open for external contribution. I'd be more than happy to add this feature to the official features repository

**Comment by dremin** [comment]
Hi @marek-siemieniuk-morawski!

The dialpad addon you linked to has been superseded by the [conference feature](https://twilio-professional-services.github.io/flex-project-template/feature-library/conference) of this repo, which we actively maintain.

With this template repo, you [create your own repository](https://github.com/twilio-professional-services/flex-project-template/generate) based on the template. Once you do this, you can customize as much as you wish! A few things to consider:
- If you already have a deployment and don't wish to deploy the full set of features from this template, you can [use the template for a specific feature](https://twilio-professional-services.github.io/flex-project-template/getting-started/use-specific-feature)
- If you wish to be able to merge in updates we make going forward, you may [add the repo history and merge in future updates](https://twilio-professional-services.github.io/flex-project-template/building/merge-future-updates)

This template aims to define a robust framework for customizing Flex to meet your needs, which sounds like it should fit what you're looking for. I would recommend [perusing the documentation](https://twilio-professional-services.github.io/flex-project-template/) to familiarize yourself with the template and its concepts to help you use it effectively going forward!
