### ISSUE TITLE
plugin validation issue when using some custom action

### ISSUE THREAD

**Issue by AllenHan-gd** [twilio-professional-services/flex-project-template#583]
Refer to the document: https://www.twilio.com/docs/flex/developer/plugins/cli/deploy-and-release#validating-a-plugin, the flex-plugin latest version add the default validate step while deploying plugin, but when using the latest version to deploy plugin, there reports some custom action issues.

These validation issue related to some action like "beforeHoldParticipant/beforeUnHoldParticipant"
Using the --bypass-validation option on the Deploy command can skip validation step

### **Steps to replicate:**

- install flex-plugin@7.0.0
- run command : twilio flex:plugins:validate

**Comment by dremin** [comment]
Hi @AllenHan-gd!

These warnings are false-positive and can be ignored. The supplied deployment scripts use the `--bypass-validation` flag to allow deploy despite the false-positive warnings.

Any issues with the CLI plugin can be reported here: https://github.com/twilio/flex-plugin-builder/issues

Thanks!
