### ISSUE TITLE
Configuration conflict between template and plugin from plugin library

### ISSUE THREAD

**Issue by RusinovIG** [twilio-professional-services/flex-project-template#645]
We're trying to test beta version of Conversational Insights. For that we had to install "Dual channel recording" plugin from plugin library in Flex admin:
![image](https://github.com/user-attachments/assets/cf9db9d6-0e66-4966-b83a-ffea1653ec24)

However after redeploy of our custom plugins with this template we noticed that "Dual channel recording" plugin was disabled, because it's disabled in the repository configuration. So this means plugins from the library share configuration with template plugins.

Is there a way to use plugins from the library together with this template? How could I split their configuration in this case?

**Comment by dremin** [comment]
Hi @RusinovIG! Yes, unfortunately currently some plugin library plugins share the configuration with the template. When running the template, we recommend disabling the plugin library counterparts and instead using the template features, as the versions available in the template are usually more up-to-date and allow you to manage configuration more holistically.

We do have future plans to resolve these conflicts, but unfortunately that is pending some plugin library and Flex UI improvements.

**Comment by RusinovIG** [comment]
Hi @dremin! Thanks for the answer. Ok, I'll check on the other side, if plugin from template could be used with "Conversational Insights" feature somehow.
