### ISSUE TITLE
Serverless domain not populated after deployment

### ISSUE THREAD

**Issue by mktobmg** [twilio-professional-services/flex-project-template#658]
Hello.

I've followed installation instructions on a Flex instance. And after deployment it should be workin ok. but i'm getting an error: **serverless_functions_domain is not set in flex config or env file**

All checks are green on the github action and it should work but i'm getting a default flex instance without the plugin nor the features loaded.

I haven't customized the template. I've just deployed as is with my account sid and api keys.

Did I miss something in the configuration?

**Comment by dremin** [comment]
Hi @mktobmg! After deployment, do you have a serverless service in your Twilio account named `custom-flex-extensions-serverless`? If not, could you please provide the deploy logs for the `deploy-packages` job? Or if you do, could you please provide the deploy logs for the `deploy-flex-config` job?

**Comment by dremin** [comment]
@mktobmg Thanks, could you also please provide the job summary output?

**Comment by mktobmg** [comment]
You mean this: 

### Job summary
 - Environment: DEV
 - Overwrite Config: true
### Configuration output

> flex-project-template@1.1.1 postinstall
> node scripts/setup-environment.mjs --packages=flex-config

Setting up ./flex-config/.env.DEV...
Installing package flex-config...



> flex-configuration@1.0.0 deploy
> node index.mjs

Populating environmental configuration data...
Fetching serverless domains...

Environment configuration summary:

---- SERVERLESS DOMAINS ------------------------------------
Serverless domain:  custom-flex-extensions-serverless-4587-dev.twil.io
Schedule manager domain:  schedule-manager-8832-dev.twil.io

Getting current configuration...
Merging current configuraton with new configuration...
Updating configuration...
Configuration updated.

### UI attributes (reduced for readability):
```
{
  common: {
    audit_log_ttl: 1209600,
    departments: [
      'General Management',
      'Marketing',
      'Operations',
      'Finance',
      'Sales',
      'Human Resources',
      'Purchasing',
      'Customer Service',
      'Recruiting'
    ],
    log_level: 'info',
    teams: [ 'Blue Team', 'Red Team', 'Gold Team', 'VIP Team' ]
  },
  features: [
    { name: 'activity_reservation_handler', enabled: false },
    { name: 'activity_skill_filter', enabled: true },
    { name: 'admin_ui', enabled: true },
    { name: 'agent_automation', enabled: true },
    { name: 'attribute_viewer', enabled: true },
    { name: 'branding', enabled: false },
    { name: 'callback_and_voicemail', enabled: true },
    { name: 'caller_id', enabled: true },
    { name: 'canned_responses', enabled: true },
    { name: 'chat_to_video_escalation', enabled: false },
    { name: 'chat_transfer', enabled: false },
    { name: 'conditional_recording', enabled: false },
    { name: 'conference', enabled: true },
    { name: 'contacts', enabled: true },
    { name: 'conversation_transfer', enabled: true },
    { name: 'custom_hold_music', enabled: false },
    { name: 'custom_transfer_directory', enabled: true },
    { name: 'datadog_log_integration', enabled: false },
    { name: 'device_manager', enabled: false },
    { name: 'dispositions', enabled: true },
    { name: 'dual_channel_recording', enabled: false },
    { name: 'emoji_picker', enabled: true },
    { name: 'enhanced_crm_container', enabled: true },
    { name: 'force_conference_region', enabled: false },
    { name: 'hang_up_by', enabled: true },
    { name: 'inline_media', enabled: true },
    { name: 'internal_call', enabled: true },
    { name: 'keyboard_shortcuts', enabled: true },
    { name: 'localization', enabled: false },
    { name: 'metrics_data_tiles', enabled: false },
    { name: 'multi_call', enabled: false },
    { name: 'omni_channel_capacity_management', enabled: false },
    { name: 'park_interaction', enabled: true },
    { name: 'pause_recording', enabled: true },
    { name: 'queues_stats_metrics', enabled: false },
    { name: 'ring_notification', enabled: false },
    { name: 'schedule_manager', enabled: true },
    { name: 'scrollable_activities', enabled: true },
    { name: 'send_audio_rec_file', enabled: true },
    { name: 'sip_support', enabled: false },
    { name: 'supervisor_barge_coach', enabled: true },
    { name: 'supervisor_capacity', enabled: true },
    { name: 'supervisor_complete_reservation', enabled: true },
    { name: 'teams_view_enhancements', enabled: true },
    { name: 'teams_view_filters', enabled: true },
    { name: 'worker_canvas_tabs', enabled: true },
    { name: 'worker_details', enabled: true }
  ],
  serverless_functions_domain: 'custom-flex-extensions-serverless-4587-dev.twil.io'
}
```

### TaskRouter skills:
- Front_DEV
- SAC_DEV
- template_example_support
- template_example_sales




-----------------------------
The full run is public here: https://github.com/Boston-Medical-Group/twilio_flex_base/actions/runs/11500721385

Thanks

**Comment by dremin** [comment]
Thanks @mktobmg! Everything from these logs looks correct--the serverless domain is being deployed, the config is picking it up, and the config is getting saved correctly.

So the question remains, why is Flex not seeing the config. Could you please double-check the account you're logged into is the correct one? Also, when in Flex, could you please run this in your browser console and verify if the output contains the config:
`Twilio.Flex.Manager.getInstance().configuration.custom_data`

**Comment by mktobmg** [comment]
Well I think something was still deploying behind the scenes because I've just checked and it seems to load all pugins now.

**Comment by dremin** [comment]
Awesome! Feel free to reopen this if it happens again and we can take another look.
