### ISSUE TITLE
Unexpected token error when updating twilio-paste to newer versions

### ISSUE THREAD

**Issue by pedrolucasfv** [twilio-professional-services/flex-project-template#665]
### Problem Description: 
I am encountering an issue when trying to update the twilio-paste library to newer versions. When running Flex, I receive the following error: unexpected token. This issue seems similar to what occurs with the emoji-mart library version 5.6.0.

### Steps to Reproduce:

```
Update twilio-paste to the latest version.
Run Flex.
The unexpected token error appears.
Expected Behavior: I expected the application to run correctly after updating the library.
```

Observed Behavior: Flex does not work and shows an unexpected token error.

Attempts to Solve:

Updated @twilio-labs/plugin-flex to version 7.0.5, as suggested in similar issues.

### Additional Information:

Version of twilio-paste used:    
- "@twilio-paste/core": "20.15.0",
- "@twilio-paste/icons": "12.7.0",

Version of plugin-flex:
- "@twilio-labs/plugin-flex:" "7.0.5"

**Comment by dremin** [comment]
Hi @pedrolucasfv! This is currently expected; the Flex plugin toolchain does not yet support building with versions of Paste newer than 17.x. Unfortunately, this is the newest version of Paste we can use in Flex plugins at this time.

**Comment by oliveiragabriel07** [comment]
Any updates on this?

**Comment by dremin** [comment]
Hi @oliveiragabriel07! Unfortunately, at this time, I do not have any updates to provide. I would recommend submitting a Support ticket with your request and use case so that our engineering team can evaluate prioritizing this.
