### ISSUE TITLE
Unable to Login to Flex in Debug Using SSO

### ISSUE THREAD

**Issue by vidhikanadia** [twilio-professional-services/flex-project-template#666]
I’m attempting to run a Twilio Flex template in debug, but I’m encountering issues at the login screen where it’s asking for a Runtime Domain. I retrieved the Runtime Domain from the Twilio Console SSO settings (e.g., `runtime-domain-1234`) and entered it, but I keep receiving an error stating, “Invalid SSO Settings.”

I’ve tried multiple variations, including entering the entire SSO URL, but the error persists, suggesting I should recheck the configuration. Logging in via the Console with an Admin account works fine, but I would like to log in with an Agent account using SSO.

I can confirm that SSO is correctly configured because I’m able to log in through SSO in the production environment, where I'm redirected to Microsoft login. However, in debug mode, Flex requires a runtime domain, and I’m unable to proceed with an Agent account login.

![image](https://github.com/user-attachments/assets/ad08e431-8d6e-4161-a220-3e788fa2c11f)
![image](https://github.com/user-attachments/assets/25620dff-e2d0-4dbd-927d-84e7bbfa1bc0)
![image](https://github.com/user-attachments/assets/7843e57b-9081-47ad-b2b5-d24da839bcb4)

**Comment by dremin** [comment]
Hi @vidhikanadia! You need to add `localhost` as a trusted domain in Flex SSO settings, and you may also need to create an `oauth` section in your `appConfig.js`. See [this doc section](https://www.twilio.com/docs/flex/admin-guide/setup/sso-configuration/self-hosted-sso#configure-the-oauth-object) for more details about that!

**Comment by vidhikanadia** [comment]
Thank you. I got it to work now!
